"""
s1 and s2 stores the sequences for which comparison has to be carried out.
Here i am using s1 as amino acid sequence of PDC-1 and s2 as amnio acid sequence of Saccharomyces cerevisiae YJM996 strain.
This code file is NOT the part of assignment.
"""
s1="MSEITLGKYLFERLKQVNVNTVFGLPGDFNLSLLDKIYEVEGMRWAGNANELNAAYAADGYARIKGMSCIITTFGVGELSALNGIAGSYAEHVGVLHVVGVPSISAQAKQLLLHHTLGNGDFTVFHRMSANISETTAMITDIATAPAEIDRCIRTTYVTQRPVYLGLPANLVDLNVPAKLLQTPIDMSLKPNDAESEKEVIDTILALVKDAKNPVILADACCSRHDVKAETKKLIDLTQFPAFVTPMGKGSIDEQHPRYGGVYVGTLSKPEVKEAVESADLILSVGALLSDFNTGSFSYSYKTKNIVEFHSDHMKIRNATFPGVQMKFVLQKLLTTIADAAKGYKPVAVPARTPANAAVPASTPLKQEWMWNQLGNFLQEGDVVIAETGTSAFGINQTTFPNNTYGISQVLWGSIGFTTGATLGAAFAAEEIDPKKRVILFIGDGSLQLTVQEISTMIRWGLKPYLFVLNNDGYTIEKLIHGPKAQYNEIQGWDHLSLLPTFGAKDYETHRVATTGEWDKLTQDKSFNDNSKIRMIEIMLPVFDAPQNLVEQAKLTAATNAKQ"
s2="MSEITLGKYLFERLSQVNCNTVFGLPGDFNLSLLDKLYEVKGMRWAGNANELNAAYAADGYARIKGMSCIITTFGVGELSALNGIAGSYAEHVGVLHVVGVPSISSQAKQLLLHHTLGNGDFTVFHRMSANISETTAMITDIANAPAEIDRCIRTTYTTQRPVYLGLPANLVDLNVPAKLLETPIDLSLKPNDAEAEAEVVRTVVELIKDAKNPVILADACASRHDVKAETKKLMDLTQFPVYVTPMGKGAIDEQHPRYGGVYVGTLSRPEVKKAVESADLILSIGALLSDFNTGSFSYSYKTKNIVEFHSDHIKIRNATFPGVQMKFALQKLLDAIPEVVKDYKPVAVPARVPITKSTPANTPMKQEWMWNHLGNFLREGDIVIAETGTSAFGINQTTFPTDVYAIVQVLWGSIGFTVGALLGATMAAEELDPKKRVILFIGDGSLQLTVQEISTMIRWGLKPYIFVLNNNGYTIEKLIHGPHAEYNEIQGWDHLALLPTFGARNYETHRVATTGEWEKLTQDKDFQDNSKIRMIEVMLPVFDAPQNLVKQAQLTAATNAKQ"

"""
A list to store the result
"""
result=[]

"""
Here we simply iterate over the two sequences and find if there is any change at any position and if there
is a change then we just append it to our result along with the position and base changed.
"""
for i in range(len(s1)):
    if(s1[i]!=s2[i]):
        t=[i+1,s1[i],s2[i]]
        result.append(t)

"""
Here we just iterate over the result list and print the desired info.
"""
for i in range(len(result)):
    print(str(result[i][0])+": "+"original: "+str(result[i][1])+"  changed: "+str(result[i][2]))